<?php $contact = config('contact', []); ?>
<footer class="site-footer">
    <div class="container footer-grid">
        <div class="footer-brand"><img src="<?= h(asset('brand/skillspark-wordmark-light.svg')) ?>" width="190" height="48" alt="SkillsPark Tech Hub"><p><?= h($site['description']) ?></p><p class="footer-tagline"><?= h($site['tagline']) ?></p></div>
        <div><h2>Company</h2><ul><li><a href="<?= h(url('/about')) ?>">About SkillsPark</a></li><li><a href="<?= h(url('/founder')) ?>">Founder</a></li><li><a href="<?= h(url('/abuja')) ?>">Serving Abuja</a></li><li><a href="<?= h(url('/edixpark')) ?>">EdixPark</a></li></ul></div>
        <div><h2>Explore</h2><ul><li><a href="<?= h(url('/services')) ?>">Services</a></li><li><a href="<?= h(url('/training')) ?>">Training</a></li><li><a href="<?= h(url('/work')) ?>">Work & Impact</a></li><li><a href="<?= h(url('/gallery')) ?>">Gallery</a></li></ul></div>
        <div><h2>Resources</h2><ul><li><a href="<?= h(url('/insights')) ?>">Insights & Tutorials</a></li><li><a href="<?= h(url('/work/case-studies')) ?>">Case Studies</a></li><li><a href="<?= h(url('/privacy-policy')) ?>">Privacy</a></li><li><a href="<?= h(url('/terms')) ?>">Terms</a></li></ul></div>
        <div class="footer-contact"><h2>Contact</h2><ul><li><a href="<?= h(url('/request-consultation')) ?>">Request a Consultation</a></li><li><a href="<?= h($contact['phone_uri']) ?>">Call: <?= h($contact['phone']) ?></a></li><li><a href="<?= h(whatsapp_url('Hello SkillsPark, I would like to make an enquiry.')) ?>" target="_blank" rel="noopener noreferrer">WhatsApp: <?= h($contact['whatsapp']) ?></a></li><li><a class="wrap-link" href="<?= h($contact['email_uri']) ?>"><?= h($contact['email']) ?></a></li><li><?= h($contact['locations']['primary']) ?></li><li><?= h($contact['locations']['abuja']) ?></li></ul><h2 class="footer-subheading">Social</h2><ul class="footer-socials"><?php foreach ($contact['socials'] as $social): $socialUrl = safe_external_url($social['url']); if ($socialUrl): ?><li><a href="<?= h($socialUrl) ?>" target="_blank" rel="noopener noreferrer"><?= h($social['label']) ?></a></li><?php endif; endforeach; ?></ul></div>
    </div>
    <div class="container footer-bottom"><p>© <?= date('Y') ?> SkillsPark Tech Hub.</p><div><a href="<?= h(url('/privacy-policy')) ?>">Privacy</a><a href="<?= h(url('/terms')) ?>">Terms</a></div></div>
</footer>
<a class="whatsapp-fab" href="<?= h(whatsapp_url('Hello SkillsPark, I would like to make an enquiry.')) ?>" rel="noopener noreferrer" target="_blank"><?= icon('chat') ?><span>Chat with SkillsPark</span></a>
