<?php

declare(strict_types=1);

// Internal permission notes must remain here and are never exposed by the gallery view.
// Photographer and ownership fields remain empty when those details have not been supplied.
return [
    ['id' => 'young-learners-software-class', 'album' => 'Practical learning', 'type' => 'image', 'title' => 'Learning by building', 'category' => 'Software classes', 'image' => '/assets/images/training/young-learners/skillspark-young-learners-software-class-768.jpg', 'srcset' => '/assets/images/training/young-learners/skillspark-young-learners-software-class-480.jpg 480w, /assets/images/training/young-learners/skillspark-young-learners-software-class-768.jpg 768w, /assets/images/training/young-learners/skillspark-young-learners-software-class-1200.jpg 1200w', 'webp_srcset' => '/assets/images/training/young-learners/skillspark-young-learners-software-class-480.webp 480w, /assets/images/training/young-learners/skillspark-young-learners-software-class-768.webp 768w, /assets/images/training/young-learners/skillspark-young-learners-software-class-1200.webp 1200w', 'video_url' => '', 'alt' => 'Young learners working on laptops during a SkillsPark technology class.', 'caption' => 'Learners practise digital skills through guided work on laptops.', 'date' => '', 'location' => '', 'consent_confirmed' => true, 'subject_type' => 'people; age not recorded', 'photographer' => '', 'image_owner' => '', 'internal_permission_note' => 'Approved for public website use in the September 2026 media batch; photographer, owner and participant age details were not supplied.', 'published' => true, 'sort_order' => 1],
    ['id' => 'hands-on-hardware-training', 'album' => 'Practical learning', 'type' => 'image', 'title' => 'Hands-on hardware training', 'category' => 'Hardware classes', 'image' => '/assets/images/training/hardware/skillspark-hands-on-hardware-training-768.jpg', 'srcset' => '/assets/images/training/hardware/skillspark-hands-on-hardware-training-480.jpg 480w, /assets/images/training/hardware/skillspark-hands-on-hardware-training-768.jpg 768w, /assets/images/training/hardware/skillspark-hands-on-hardware-training-1200.jpg 1200w', 'webp_srcset' => '/assets/images/training/hardware/skillspark-hands-on-hardware-training-480.webp 480w, /assets/images/training/hardware/skillspark-hands-on-hardware-training-768.webp 768w, /assets/images/training/hardware/skillspark-hands-on-hardware-training-1200.webp 1200w', 'video_url' => '', 'alt' => 'Participants working on an open desktop computer during SkillsPark hardware training.', 'caption' => 'Participants examine computer components during a supervised practical session.', 'date' => '', 'location' => '', 'consent_confirmed' => true, 'subject_type' => 'people; age not recorded', 'photographer' => '', 'image_owner' => '', 'internal_permission_note' => 'Approved for public website use in the September 2026 media batch; photographer, owner and participant age details were not supplied.', 'published' => true, 'sort_order' => 2],
    ['id' => 'video-editing-training', 'album' => 'Creative skills', 'type' => 'image', 'title' => 'Video-editing practice', 'category' => 'Projects', 'image' => '/assets/images/training/creative-media/skillspark-video-editing-training-768.jpg', 'srcset' => '/assets/images/training/creative-media/skillspark-video-editing-training-480.jpg 480w, /assets/images/training/creative-media/skillspark-video-editing-training-768.jpg 768w, /assets/images/training/creative-media/skillspark-video-editing-training-1200.jpg 1200w', 'webp_srcset' => '/assets/images/training/creative-media/skillspark-video-editing-training-480.webp 480w, /assets/images/training/creative-media/skillspark-video-editing-training-768.webp 768w, /assets/images/training/creative-media/skillspark-video-editing-training-1200.webp 1200w', 'video_url' => '', 'alt' => 'A participant practising video editing on a laptop during SkillsPark training.', 'caption' => 'Practical creative-media training connects software tools with real editing work.', 'date' => '', 'location' => '', 'consent_confirmed' => true, 'subject_type' => 'people; age not recorded', 'photographer' => '', 'image_owner' => '', 'internal_permission_note' => 'Approved for public website use in the September 2026 media batch; photographer, owner and participant age details were not supplied.', 'published' => true, 'sort_order' => 3],
    ['id' => 'hardware-program-group', 'album' => 'Practical learning', 'type' => 'image', 'title' => 'Hardware programme group', 'category' => 'Hardware classes', 'image' => '/assets/images/training/hardware/skillspark-hardware-program-group-768.jpg', 'srcset' => '/assets/images/training/hardware/skillspark-hardware-program-group-480.jpg 480w, /assets/images/training/hardware/skillspark-hardware-program-group-768.jpg 768w, /assets/images/training/hardware/skillspark-hardware-program-group-1200.jpg 1200w', 'webp_srcset' => '/assets/images/training/hardware/skillspark-hardware-program-group-480.webp 480w, /assets/images/training/hardware/skillspark-hardware-program-group-768.webp 768w, /assets/images/training/hardware/skillspark-hardware-program-group-1200.webp 1200w', 'video_url' => '', 'alt' => 'A SkillsPark hardware training group standing behind open desktop computers.', 'caption' => 'A group photograph following practical work with desktop computer components.', 'date' => '', 'location' => '', 'consent_confirmed' => true, 'subject_type' => 'people; age not recorded', 'photographer' => '', 'image_owner' => '', 'internal_permission_note' => 'Approved for public website use in the September 2026 media batch; photographer, owner and participant age details were not supplied.', 'published' => true, 'sort_order' => 4],
];
