<?php

declare(strict_types=1);

// evidence_status is an internal editorial control: verified, needs_details,
// needs_media, needs_permission or draft. It is never displayed publicly.
return [
    'areas' => [
        ['id' => 'international-partnerships', 'title' => 'International Partnerships', 'summary' => 'Training relationships that connect SkillsPark with institutions beyond Nigeria, published with careful verification.', 'icon' => 'handshake', 'published' => true, 'sort_order' => 1],
        ['id' => 'learner-entrepreneurship', 'title' => 'Learner Entrepreneurship', 'summary' => 'Practical learning that participants can apply to independent work, enterprise and new opportunities.', 'icon' => 'transform', 'published' => true, 'sort_order' => 2],
        ['id' => 'women-youth-skills', 'title' => 'Women & Youth Skills', 'summary' => 'Accessible creative and technology learning that supports young people in applying useful skills.', 'icon' => 'learn', 'published' => true, 'sort_order' => 3],
        ['id' => 'siwes-practical-training', 'title' => 'SIWES & Practical Training', 'summary' => 'Hands-on technology exposure that helps students connect academic learning with practical work.', 'icon' => 'code', 'published' => true, 'sort_order' => 4],
        ['id' => 'community-learning', 'title' => 'Community Learning', 'summary' => 'Free classes, workshops and online tutorials that make practical technology learning more accessible.', 'icon' => 'learn', 'published' => true, 'sort_order' => 5],
        ['id' => 'technology-solutions', 'title' => 'Technology Solutions', 'summary' => 'Design and development support for organizations creating useful technology products and digital solutions.', 'icon' => 'products', 'published' => true, 'sort_order' => 6],
    ],
    'stories' => [
        ['id' => 'practical-training', 'title' => 'Practical technology training', 'category' => 'Practical Learning', 'summary' => 'SkillsPark has delivered software and hardware classes for children and adults, using guided practice and hands-on work.', 'url' => '/work/case-studies', 'evidence_status' => 'verified', 'verification_needed' => [], 'published' => true, 'sort_order' => 1],
        ['id' => 'advista-hub-outcome', 'title' => 'A learner launched Advista Hub', 'category' => 'Learner Entrepreneurship', 'summary' => 'A learner trained by SkillsPark later established a company named Advista Hub.', 'url' => '/work/case-studies/advista-hub-learner-outcome', 'evidence_status' => 'needs_details', 'verification_needed' => ['Learner identity and publication permission', 'SkillsPark programme and skills learned', 'Launch date', 'Website and approved media', 'Testimonial'], 'published' => true, 'sort_order' => 2],
        ['id' => 'community-access', 'title' => 'Learning beyond paid programmes', 'category' => 'Community Learning', 'summary' => 'SkillsPark has provided free classes, practical workshops and free online tutorials to make technology learning more accessible.', 'url' => '/insights', 'evidence_status' => 'needs_media', 'verification_needed' => ['Dates and programme records', 'Approved supporting media', 'Tutorial links'], 'published' => true, 'sort_order' => 3],
        ['id' => 'dubai-training-collaboration', 'title' => 'International training collaboration', 'category' => 'Partnerships', 'summary' => 'SkillsPark established a partnership with an Aptech computer training institute in Dubai.', 'url' => '/work/partnerships', 'evidence_status' => 'needs_details', 'verification_needed' => ['Official institution and branch name', 'Date', 'Scope', 'Public logo permission', 'Agreement or certificate evidence'], 'published' => true, 'sort_order' => 4],
        ['id' => 'women-graphic-design', 'title' => 'Graphic-design skills for young women', 'category' => 'Women & Youth Skills', 'summary' => 'SkillsPark has provided graphic-design training to young women, and some participants now apply those skills through freelance work from home.', 'url' => '/training', 'evidence_status' => 'needs_media', 'verification_needed' => ['Programme details', 'Approved programme-specific media', 'Participant permission for individual stories'], 'published' => true, 'sort_order' => 5],
        ['id' => 'siwes-training', 'title' => 'Practical experience for SIWES students', 'category' => 'SIWES', 'summary' => 'SkillsPark has provided SIWES students with hands-on technology exposure and practical learning.', 'url' => '/training/students-and-graduates', 'evidence_status' => 'needs_details', 'verification_needed' => ['Institutions', 'Dates', 'Placement duration', 'Student counts and permissions'], 'published' => true, 'sort_order' => 6],
        ['id' => 'organization-technology-work', 'title' => 'Technology work for organizations', 'category' => 'Technology Solutions', 'summary' => 'SkillsPark supports organizations with the design and development of technology products and digital solutions.', 'url' => '/services/technology-and-software', 'evidence_status' => 'needs_permission', 'verification_needed' => ['Client identities and publication permission', 'Project names and scope', 'Approved screenshots', 'Verified outcomes'], 'published' => true, 'sort_order' => 7],
    ],
];
