<?php

declare(strict_types=1);

return [
    ['title' => 'What makes technology training practical?', 'slug' => 'what-makes-technology-training-practical', 'category' => 'Learning', 'summary' => 'A useful learning experience moves from explanation to guided practice, reflection and an outcome the learner can demonstrate.', 'body' => 'Practical technology training is not simply a longer list of tools. It gives learners a clear problem, enough explanation to begin, guided room to make mistakes and a project they can discuss. The facilitator watches how learners reason, not only whether they copy a sequence successfully. This approach helps participants build confidence that can transfer to new tasks.', 'published' => true, 'featured' => true, 'sort_order' => 1, 'seo_title' => 'What Makes Technology Training Practical? | SkillsPark', 'seo_description' => 'A clear look at project-based learning, guided practice and transferable technology skills.'],
    ['title' => 'A simple digital-presence check for growing organizations', 'slug' => 'digital-presence-check', 'category' => 'Business', 'summary' => 'Start with discoverability, credibility, consistency and a clear path for people to take action.', 'body' => 'A useful digital-presence review begins with basic questions. Can people find accurate information? Does the organization look consistent across its active channels? Can a visitor understand the offer and make contact without confusion? Are staff able to maintain what is published? Addressing these foundations often creates more value than opening another unused channel.', 'published' => true, 'featured' => true, 'sort_order' => 2, 'seo_title' => 'A Digital-Presence Check for Growing Organizations | SkillsPark', 'seo_description' => 'Four practical questions for improving organizational visibility, credibility and enquiries.'],
    ['title' => 'Introducing children to technology responsibly', 'slug' => 'children-technology-responsibly', 'category' => 'Education', 'summary' => 'Good children’s programs balance curiosity, creativity, safety, age-appropriate challenge and adult responsibility.', 'body' => 'Technology programs for children should make room for exploration without ignoring safeguarding. Activities need a clear purpose, age-appropriate language and manageable sessions. Adults should agree media consent, device access and supervision in advance. The strongest projects let young learners create, explain and improve something while understanding responsible digital behaviour.', 'published' => true, 'featured' => true, 'sort_order' => 3, 'seo_title' => 'Introducing Children to Technology Responsibly | SkillsPark', 'seo_description' => 'Principles for safe, creative and age-aware children’s technology programs.'],
];
