<?php
declare(strict_types=1);

return [
    ['title' => 'Practical Software Classes', 'slug' => 'practical-software-classes', 'category' => 'Training', 'date' => '', 'location' => 'Kano/Zaria Road area', 'objective' => 'Help children and adults gain practical experience with software and digital tools.', 'challenge' => 'Learners need guided practice that connects concepts to things they can make and explain.', 'approach' => 'Sessions use demonstrations, supervised exercises and project work, adjusted to the participants’ level.', 'services' => ['Technology training', 'Project-based learning'], 'technologies' => ['Software development foundations', 'Digital productivity'], 'outcomes' => ['Software classes have been conducted for children and adults.'], 'metrics' => [], 'testimonial' => '', 'image' => '', 'gallery' => [], 'video' => '', 'related_service' => 'technology-and-software', 'evidence_status' => 'verified', 'verification_needed' => [], 'participant_permission' => '', 'featured' => true, 'published' => true, 'sort_order' => 1, 'seo_title' => 'Practical Software Classes | SkillsPark Work', 'seo_description' => 'How SkillsPark structures practical software learning for children and adults.'],
    ['title' => 'Hands-on Hardware Classes', 'slug' => 'hands-on-hardware-classes', 'category' => 'Hardware', 'date' => '', 'location' => 'Kano/Zaria Road area', 'objective' => 'Introduce participants to computer hardware, safe handling and diagnosis principles.', 'challenge' => 'Hardware skills become meaningful when learners can identify parts and reason through practical faults.', 'approach' => 'Facilitated sessions combine explanation with supervised handling, diagnosis and maintenance exercises.', 'services' => ['Hardware training', 'Technical skills development'], 'technologies' => ['Computer components', 'Maintenance principles'], 'outcomes' => ['Hardware classes have been conducted for children and adults.'], 'metrics' => [], 'testimonial' => '', 'image' => '', 'gallery' => [], 'video' => '', 'related_service' => 'hardware-and-technical-support', 'evidence_status' => 'verified', 'verification_needed' => [], 'participant_permission' => '', 'featured' => true, 'published' => true, 'sort_order' => 2, 'seo_title' => 'Hands-on Hardware Classes | SkillsPark Work', 'seo_description' => 'Practical computer hardware learning designed around safe, supervised participation.'],
    // Public copy is intentionally limited to the owner-verified outcome until the fields below are confirmed.
    ['title' => 'Learner Entrepreneurship: Advista Hub', 'slug' => 'advista-hub-learner-outcome', 'category' => 'Learner outcome', 'date' => '', 'location' => '', 'objective' => 'A learner trained by SkillsPark later established a company named Advista Hub.', 'challenge' => '', 'approach' => 'SkillsPark contributed through practical training completed by the learner.', 'services' => ['Practical technology training'], 'technologies' => [], 'outcomes' => ['The learner later established Advista Hub.'], 'metrics' => [], 'testimonial' => '', 'image' => '', 'gallery' => [], 'video' => '', 'related_service' => 'technology-and-software', 'evidence_status' => 'needs_details', 'verification_needed' => ['Learner/founder identity and permission', 'SkillsPark programme', 'Skills learned', 'Launch date', 'Website', 'Approved images', 'Testimonial'], 'participant_permission' => '', 'featured' => true, 'published' => true, 'sort_order' => 3, 'seo_title' => 'Advista Hub Learner Outcome | SkillsPark Work', 'seo_description' => 'A verified SkillsPark learner outcome: a learner trained by SkillsPark later established Advista Hub.'],
];
