<?php
declare(strict_types=1);

return [
    ['title' => 'Practical Software Classes', 'slug' => 'practical-software-classes', 'category' => 'Training', 'date' => '', 'location' => 'Kano/Zaria Road area', 'objective' => 'Help children and adults gain practical experience with software and digital tools.', 'challenge' => 'Learners need guided practice that connects concepts to things they can make and explain.', 'approach' => 'Sessions use demonstrations, supervised exercises and project work, adjusted to the participants’ level.', 'services' => ['Technology training', 'Project-based learning'], 'technologies' => ['Software development foundations', 'Digital productivity'], 'outcomes' => ['Software classes have been conducted for children and adults.'], 'metrics' => [], 'testimonial' => '', 'image' => '', 'gallery' => [], 'video' => '', 'related_service' => 'technology-and-software', 'evidence_status' => 'verified', 'verification_needed' => [], 'participant_permission' => '', 'featured' => true, 'published' => true, 'sort_order' => 1, 'seo_title' => 'Practical Software Classes | SkillsPark Work', 'seo_description' => 'How SkillsPark structures practical software learning for children and adults.'],
    ['title' => 'Hands-on Hardware Classes', 'slug' => 'hands-on-hardware-classes', 'category' => 'Hardware', 'date' => '', 'location' => 'Kano/Zaria Road area', 'objective' => 'Introduce participants to computer hardware, safe handling and diagnosis principles.', 'challenge' => 'Hardware skills become meaningful when learners can identify parts and reason through practical faults.', 'approach' => 'Facilitated sessions combine explanation with supervised handling, diagnosis and maintenance exercises.', 'services' => ['Hardware training', 'Technical skills development'], 'technologies' => ['Computer components', 'Maintenance principles'], 'outcomes' => ['Hardware classes have been conducted for children and adults.'], 'metrics' => [], 'testimonial' => '', 'image' => '', 'gallery' => [], 'video' => '', 'related_service' => 'hardware-and-technical-support', 'evidence_status' => 'verified', 'verification_needed' => [], 'participant_permission' => '', 'featured' => true, 'published' => true, 'sort_order' => 2, 'seo_title' => 'Hands-on Hardware Classes | SkillsPark Work', 'seo_description' => 'Practical computer hardware learning designed around safe, supervised participation.'],
    // Public copy is intentionally limited to the owner-verified outcome until the fields below are confirmed.
    ['title' => 'From Learning Digital Skills to Building Advista Hub', 'slug' => 'advista-hub-learner-outcome', 'category' => 'Learner entrepreneurship', 'date' => '', 'location' => '', 'objective' => 'A learner trained through SkillsPark later went on to establish Advista Hub.', 'challenge' => '', 'approach' => 'SkillsPark contributed practical learning in digital skills that the learner later applied to an advertising-focused platform.', 'services' => ['Practical digital-skills training'], 'technologies' => ['Video editing', 'Graphic design', 'Website design', 'Digital presentation and marketing'], 'outcomes' => ['Advista Hub helps promote people, products and businesses using practical digital skills.'], 'metrics' => [], 'testimonial' => '', 'image' => '/assets/images/impact/advista-hub/skillspark-advista-hub-learner-outcome-768.jpg', 'image_srcset' => '/assets/images/impact/advista-hub/skillspark-advista-hub-learner-outcome-480.jpg 480w, /assets/images/impact/advista-hub/skillspark-advista-hub-learner-outcome-768.jpg 768w, /assets/images/impact/advista-hub/skillspark-advista-hub-learner-outcome-1200.jpg 1200w', 'image_webp_srcset' => '/assets/images/impact/advista-hub/skillspark-advista-hub-learner-outcome-480.webp 480w, /assets/images/impact/advista-hub/skillspark-advista-hub-learner-outcome-768.webp 768w, /assets/images/impact/advista-hub/skillspark-advista-hub-learner-outcome-1200.webp 1200w', 'image_width' => 1200, 'image_height' => 900, 'image_alt' => 'Advista Hub presentation displayed during a SkillsPark activity.', 'gallery' => [], 'video' => '', 'related_service' => 'technology-and-software', 'evidence_status' => 'needs_details', 'verification_needed' => ['Learner identity and publication permission', 'Programme details', 'Launch date', 'Testimonial'], 'participant_permission' => '', 'featured' => true, 'published' => true, 'sort_order' => 3, 'seo_title' => 'Advista Hub Learner Outcome | SkillsPark Work', 'seo_description' => 'How a learner trained through SkillsPark later established Advista Hub and applied practical digital skills.'],
];
