<?php

declare(strict_types=1);

$commonProcess = [
    ['title' => 'Discover', 'text' => 'Clarify the audience, problem, constraints and definition of success.'],
    ['title' => 'Plan', 'text' => 'Agree the scope, priorities, responsibilities and practical delivery path.'],
    ['title' => 'Create', 'text' => 'Build in visible stages, with review points that keep the work aligned.'],
    ['title' => 'Launch and improve', 'text' => 'Deploy carefully, transfer knowledge and identify measured next steps.'],
];

return [
    ['title' => 'Technology & Software Solutions', 'slug' => 'technology-and-software', 'icon' => 'code', 'summary' => 'Purpose-built digital tools, portals and software support for operational needs.', 'problem' => 'Manual processes, disconnected information and unsuitable off-the-shelf tools can slow teams down.', 'customers' => ['Schools', 'Businesses', 'NGOs', 'Institutions'], 'deliverables' => ['Requirements discovery', 'Web-based portals', 'Custom software modules', 'Systems integration guidance', 'Deployment and handover'], 'approach' => 'We begin with the actual workflow, then choose the smallest reliable solution that can be supported over time.', 'process' => $commonProcess, 'faqs' => [['q' => 'Do you build every system from scratch?', 'a' => 'No. We assess whether an existing platform, a focused integration or custom development is the most sensible option.'], ['q' => 'Can you work in phases?', 'a' => 'Yes. Phased delivery is often useful when priorities, budgets or internal capacity need to be balanced.']], 'featured' => true, 'published' => true, 'sort_order' => 1, 'seo_title' => 'Technology and Software Solutions | SkillsPark', 'seo_description' => 'Practical portals, software and technology solutions for schools, businesses and organizations.'],
    ['title' => 'Web Design & Development', 'slug' => 'web-design-and-development', 'icon' => 'browser', 'summary' => 'Fast, credible websites designed around business goals, content and real audiences.', 'problem' => 'An outdated, unclear or missing website can weaken trust and make enquiries harder to win.', 'customers' => ['Businesses', 'Schools', 'Startups', 'Professionals', 'Organizations'], 'deliverables' => ['Content structure', 'Responsive interface design', 'Website development', 'Performance and accessibility work', 'Launch support'], 'approach' => 'We connect strategy, clear writing, purposeful design and maintainable development in one delivery process.', 'process' => $commonProcess, 'faqs' => [['q' => 'Will the website work on phones?', 'a' => 'Yes. Responsive behaviour and usable mobile navigation are part of the core build.'], ['q' => 'Can our team update the content?', 'a' => 'We agree a suitable maintenance approach based on the project, team and hosting environment.']], 'featured' => true, 'published' => true, 'sort_order' => 2, 'seo_title' => 'Web Design and Development | SkillsPark', 'seo_description' => 'Professional websites for businesses, schools and organizations, built for clarity and performance.'],
    ['title' => 'Business Digital Transformation', 'slug' => 'business-digital-transformation', 'icon' => 'transform', 'summary' => 'Practical improvements to digital presence, workflows, documentation and staff capability.', 'problem' => 'Growth is difficult when processes are informal, repetitive or unsupported by the right digital tools.', 'customers' => ['SMEs', 'NGOs', 'Corporate teams', 'Institutions'], 'deliverables' => ['Digital-presence assessment', 'Workflow mapping', 'Technology recommendations', 'Documentation systems', 'Staff capacity development'], 'approach' => 'We prioritize changes that are understandable, adoptable and proportionate to the organization’s current stage.', 'process' => $commonProcess, 'faqs' => [['q' => 'Is this only for large companies?', 'a' => 'No. The scope can be shaped for a growing small business, a team or a larger institution.'], ['q' => 'Do you recommend specific tools?', 'a' => 'Only after understanding the workflow, users, budget and long-term support needs.']], 'featured' => true, 'published' => true, 'sort_order' => 3, 'seo_title' => 'Business Digital Transformation | SkillsPark', 'seo_description' => 'Digital strategy, workflow improvement and staff capability for growing organizations.'],
    ['title' => 'Branding & Graphic Design', 'slug' => 'branding-and-graphic-design', 'icon' => 'pen', 'summary' => 'Coherent visual identity and communication assets that help organizations look prepared.', 'problem' => 'Inconsistent or improvised visuals make it harder for audiences to recognize and trust a brand.', 'customers' => ['Businesses', 'Programs', 'Schools', 'Organizations'], 'deliverables' => ['Visual identity direction', 'Brand guidelines', 'Campaign graphics', 'Print-ready materials', 'Digital asset systems'], 'approach' => 'Design choices are grounded in audience, context and the practical places the brand needs to work.', 'process' => $commonProcess, 'faqs' => [['q' => 'Can you work with an existing logo?', 'a' => 'Yes. We can organize and extend an existing identity without replacing recognizable assets unnecessarily.']], 'featured' => true, 'published' => true, 'sort_order' => 4, 'seo_title' => 'Branding and Graphic Design | SkillsPark', 'seo_description' => 'Brand identity, graphic design and practical communication assets for organizations.'],
    ['title' => 'Video & Media Production', 'slug' => 'video-and-media-production', 'icon' => 'video', 'summary' => 'Photography, video and motion content planned for clear communication and useful distribution.', 'problem' => 'Important work is often poorly documented or turned into media without a clear message or use plan.', 'customers' => ['Programs', 'Businesses', 'Schools', 'Partners'], 'deliverables' => ['Production planning', 'Photography', 'Video production', 'Editing', 'Motion graphics and delivery formats'], 'approach' => 'We plan around the story, permissions, audience and channels before production begins.', 'process' => $commonProcess, 'faqs' => [['q' => 'Do you handle participant consent?', 'a' => 'Consent and responsible media handling should be agreed before filming, especially when children are involved.']], 'featured' => true, 'published' => true, 'sort_order' => 5, 'seo_title' => 'Video and Media Production | SkillsPark', 'seo_description' => 'Photography, video production, editing and motion content for programs and organizations.'],
    ['title' => '3D Modelling & Animation', 'slug' => '3d-modelling-and-animation', 'icon' => 'cube', 'summary' => '3D visualisation and animation for ideas that benefit from dimensional explanation.', 'problem' => 'Some products, spaces and concepts are difficult to communicate with flat images alone.', 'customers' => ['Creative teams', 'Businesses', 'Educators', 'Project owners'], 'deliverables' => ['3D asset planning', 'Modelling', 'Materials and lighting', 'Animation', 'Rendered delivery formats'], 'approach' => 'We define the communication goal and required level of detail before investing in production.', 'process' => $commonProcess, 'faqs' => [['q' => 'What affects delivery time?', 'a' => 'Complexity, realism, animation length, source materials and revision requirements all affect scope.']], 'featured' => false, 'published' => true, 'sort_order' => 6, 'seo_title' => '3D Modelling and Animation | SkillsPark', 'seo_description' => '3D assets, visualisation and animation for business, education and creative communication.'],
    ['title' => 'Social Media & Digital Presence', 'slug' => 'social-media-and-digital-presence', 'icon' => 'signal', 'summary' => 'A more consistent online presence supported by practical content and asset systems.', 'problem' => 'Irregular messaging, scattered profiles and inconsistent visuals reduce the value of digital channels.', 'customers' => ['SMEs', 'Entrepreneurs', 'Schools', 'Organizations'], 'deliverables' => ['Presence audit', 'Channel priorities', 'Profile improvement', 'Content systems', 'Reusable social assets'], 'approach' => 'We focus on sustainable habits and useful channels rather than activity for its own sake.', 'process' => $commonProcess, 'faqs' => [['q' => 'Do we need to use every platform?', 'a' => 'No. We recommend channels based on the audience, available capacity and communication goal.']], 'featured' => false, 'published' => true, 'sort_order' => 7, 'seo_title' => 'Social Media and Digital Presence | SkillsPark', 'seo_description' => 'Digital-presence assessment, social media improvement and practical content systems.'],
    ['title' => 'Hardware & Technical Support', 'slug' => 'hardware-and-technical-support', 'icon' => 'tools', 'summary' => 'Computer hardware guidance, repairs and practical technical support for reliable everyday work.', 'problem' => 'Unreliable devices and weak maintenance practices interrupt learning and business operations.', 'customers' => ['Individuals', 'Schools', 'Small teams', 'Training centres'], 'deliverables' => ['Technical assessment', 'Repair guidance', 'Hardware support', 'Preventive maintenance advice', 'User orientation'], 'approach' => 'We diagnose before recommending repair or replacement, and explain decisions in plain language.', 'process' => $commonProcess, 'faqs' => [['q' => 'Can every device be repaired?', 'a' => 'No. We assess feasibility and communicate when repair is unsafe, uneconomical or outside scope.']], 'featured' => false, 'published' => true, 'sort_order' => 8, 'seo_title' => 'Hardware and Technical Support | SkillsPark', 'seo_description' => 'Computer hardware assessment, repair guidance and practical technical support.'],
];
