<?php

declare(strict_types=1);

return [
    'audiences' => [
        ['title' => 'Children & Teenagers', 'slug' => 'children-and-teenagers', 'summary' => 'Guided, age-aware technology experiences that build curiosity, confidence and safe creative habits.', 'skills' => ['Coding foundations', 'Robotics', 'Creative design', 'Digital safety', 'Project presentation'], 'outcomes' => ['Understand core digital concepts', 'Create a guided practical project', 'Communicate what was learned'], 'format' => 'Small-group or institutional delivery', 'duration' => 'Configured for the selected program', 'location' => 'Available locations are confirmed during enquiry', 'requirements' => 'Age, device access and guardian or school consent are confirmed before delivery', 'published' => true, 'sort_order' => 1, 'seo_title' => 'Technology Training for Children and Teenagers | SkillsPark', 'seo_description' => 'Project-based coding, robotics and creative technology programs for young learners.'],
        ['title' => 'Students & Graduates', 'slug' => 'students-and-graduates', 'summary' => 'Applied digital skills and portfolio-focused projects for employment, enterprise and continued learning.', 'skills' => ['Web development', 'UI/UX', 'Graphic design', 'AI productivity', 'Digital business'], 'outcomes' => ['Complete practical project work', 'Develop stronger problem-solving habits', 'Identify a realistic development pathway'], 'format' => 'Cohort, workshop or partner delivery', 'duration' => 'Depends on depth and selected skills', 'location' => 'Confirmed for each engagement', 'requirements' => 'Requirements vary by pathway and are shared before enrolment', 'published' => true, 'sort_order' => 2, 'seo_title' => 'Digital Skills for Students and Graduates | SkillsPark', 'seo_description' => 'Practical technology training for portfolio development, work and entrepreneurship.'],
        ['title' => 'Adults & Entrepreneurs', 'slug' => 'adults-and-entrepreneurs', 'summary' => 'Useful technology skills for work, productivity, business development and independent projects.', 'skills' => ['Digital productivity', 'Web and design skills', 'AI tools', 'Online business', 'Content creation'], 'outcomes' => ['Use selected tools with more confidence', 'Apply skills to a real work or business need', 'Leave with practical next steps'], 'format' => 'Workshop, short course or tailored small-group training', 'duration' => 'Configured around the learning goal', 'location' => 'Confirmed during enquiry', 'requirements' => 'No assumptions are made about prior experience; entry needs are agreed first', 'published' => true, 'sort_order' => 3, 'seo_title' => 'Technology Training for Adults and Entrepreneurs | SkillsPark', 'seo_description' => 'Practical digital skills for productivity, employment, business and creative work.'],
        ['title' => 'Schools', 'slug' => 'schools', 'summary' => 'Technology programs, clubs and staff development aligned with a school\'s learners, calendar and resources.', 'skills' => ['Coding and robotics', 'Digital creativity', 'Teacher productivity', 'Technology planning', 'Responsible technology use'], 'outcomes' => ['Structured learning experiences', 'Better staff confidence with selected tools', 'A realistic plan for ongoing technology development'], 'format' => 'On-site, partner venue or blended institutional delivery', 'duration' => 'Agreed with the school', 'location' => 'Serving schools in agreed locations, including Abuja outreach', 'requirements' => 'Safeguarding, consent, facilities and responsibilities are agreed in advance', 'published' => true, 'sort_order' => 4, 'seo_title' => 'Technology Programs and Training for Schools | SkillsPark', 'seo_description' => 'Student programs, technology clubs and staff capacity development for schools.'],
        ['title' => 'Corporate Training', 'slug' => 'corporate-training', 'summary' => 'Role-relevant staff training designed around organizational priorities and real workplace tasks.', 'skills' => ['Digital productivity', 'AI at work', 'Documentation systems', 'Digital communication', 'Team-specific technology'], 'outcomes' => ['Apply tools to real responsibilities', 'Use shared methods more consistently', 'Identify workflow improvements'], 'format' => 'On-site, remote or blended team delivery', 'duration' => 'Defined after a needs assessment', 'location' => 'Delivered for organizations in agreed locations', 'requirements' => 'A brief needs assessment identifies roles, tools and expected outcomes', 'published' => true, 'sort_order' => 5, 'seo_title' => 'Corporate Technology Training | SkillsPark', 'seo_description' => 'Tailored digital productivity, AI and technology training for teams and organizations.'],
    ],
    'programs' => [
        ['title' => 'Digital Skills Switch', 'slug' => 'digital-skills-switch', 'eyebrow' => 'Build a digital foundation', 'summary' => 'Explore different skills. Discover where you want to go deeper.', 'body' => 'Digital Skills Switch introduces learners to several practical digital areas, helping them build confidence with technology while discovering the skills they may want to develop further. Instead of beginning with theory alone, learners work directly with tools and practical tasks across creative, web and business applications. For learners with little or no previous computer experience, SkillsPark may begin with laptop, touchpad, file and basic computer confidence through practical design activity.', 'audience' => 'Beginners who want broad exposure before choosing a deeper path', 'approach' => 'A broad foundation with practical, hands-on learning and supporting theory.', 'skills' => ['Web Design using WordPress', 'Graphic Design using CorelDRAW', 'Video Content Creation and Editing using Filmora', 'Blogging using Blogger', 'Photography and image editing using camera and Photoshop', 'Entrepreneurship and Business Skills'], 'related_audiences' => ['Students & Graduates', 'Adults & Entrepreneurs'], 'image' => 'images/training/digital-skills-switch-graphic-design/digital-skills-switch-graphic-design', 'image_width' => 1200, 'image_height' => 675, 'image_alt' => 'SkillsPark learners building computer confidence through practical graphic design.', 'seo_title' => 'Digital Skills Switch | SkillsPark Tech Hub', 'seo_description' => 'SkillsPark Digital Skills Switch introduces practical creative, web and business digital skills without overpromising instant mastery.', 'featured' => true, 'published' => true, 'sort_order' => 1],
        ['title' => 'Digital Skills Masterclass', 'slug' => 'digital-skills-masterclass', 'eyebrow' => 'Specialized learning', 'summary' => 'Choose one field and go deeper.', 'body' => 'Digital Skills Masterclass is designed for learners who want focused development in one area. Rather than moving quickly across several disciplines, participants concentrate on a selected field and develop their understanding through guided practice, projects and increasingly advanced work. Tool choices depend on the selected class and confirmed delivery plan.', 'audience' => 'Learners ready to specialize in one creative, software or digital field', 'approach' => 'Focused practice, guided projects, feedback and increasingly advanced work.', 'skills' => ['Web Development', '3D Modelling & Animation', 'UI/UX Design', 'VFX & Motion Graphics', 'Digital Marketing', 'Business Skills', '2D Animation', 'AI-Assisted Animation'], 'related_audiences' => ['Students & Graduates', 'Adults & Entrepreneurs'], 'seo_title' => 'Digital Skills Masterclass | SkillsPark Tech Hub', 'seo_description' => 'Choose one practical digital field and go deeper through guided SkillsPark project work.', 'featured' => true, 'published' => true, 'sort_order' => 2],
        ['title' => 'Technical Skills Program', 'slug' => 'technical-skills-program', 'eyebrow' => 'Practical technical skills', 'summary' => 'Learn by working directly with technology.', 'body' => 'The Technical Skills Program focuses on practical abilities that require learners to understand, diagnose, build or repair technology. Training combines explanation with direct hands-on work so participants can develop confidence working with real devices, components and systems. Computer maintenance content is supported by verified SkillsPark hardware-training evidence.', 'audience' => 'Learners who want practical foundations in devices, components and systems', 'approach' => 'Hands-on technical explanation, diagnosis practice and supervised work with technology.', 'skills' => ['Smartphone Repairs', 'Computer Maintenance', 'Robotics fundamentals', 'Simple robot construction', 'Programming concepts using C++'], 'related_audiences' => ['Children & Teenagers', 'Students & Graduates', 'Adults & Entrepreneurs'], 'image' => 'images/training/computer-hardware/computer-hardware-training-group', 'image_width' => 1200, 'image_height' => 900, 'image_alt' => 'SkillsPark learners in a hands-on computer hardware training session.', 'seo_title' => 'Technical Skills Program | SkillsPark Tech Hub', 'seo_description' => 'SkillsPark Technical Skills Program covers practical foundations in hardware, repair, maintenance and robotics concepts.', 'featured' => true, 'published' => true, 'sort_order' => 3],
        ['title' => 'Business in the Digital Age', 'slug' => 'business-in-the-digital-age', 'eyebrow' => 'Business & digital growth', 'summary' => 'Practical technology for people building businesses.', 'body' => 'Business in the Digital Age helps entrepreneurs understand how modern digital tools can support everyday business activity. Learners explore practical ways to use technology, artificial intelligence, social platforms, digital marketing, branding and other tools to improve how they communicate, organize and grow their businesses.', 'audience' => 'Business owners, entrepreneurs and startup founders', 'approach' => 'Practical business-focused learning connected to communication, organization and growth.', 'skills' => ['Entrepreneurial digital skills', 'AI for Business', 'Social Media Marketing', 'Digital Marketing', 'Product Branding', 'Packaging'], 'related_audiences' => ['Adults & Entrepreneurs', 'Corporate Training'], 'seo_title' => 'Business in the Digital Age | SkillsPark Tech Hub', 'seo_description' => 'Practical SkillsPark training for entrepreneurs using digital tools, AI, marketing, branding and business technology.', 'featured' => true, 'published' => true, 'sort_order' => 4],
        ['title' => 'Train the Trainers', 'slug' => 'train-the-trainers', 'eyebrow' => 'Learn to teach', 'summary' => 'Turn practical knowledge into the ability to guide others.', 'body' => 'SkillsPark\'s Train the Trainers program helps learners develop the ability to pass on the skills they have gained. Participants strengthen communication, classroom management, public speaking, leadership and confidence while learning how to guide others effectively. Some participants may support SkillsPark learning as tutors or instructors, creating an early pathway into practical work while extending knowledge to more people.', 'audience' => 'Learners ready to strengthen leadership and instructional ability', 'approach' => 'Communication practice, facilitation habits and guided reflection on how people learn.', 'skills' => ['Communication', 'Classroom management', 'Public speaking', 'Leadership', 'Confidence', 'Instructional ability'], 'related_audiences' => ['Students & Graduates', 'Corporate Training'], 'image' => 'images/training/train-the-trainers/train-the-trainers', 'image_width' => 1200, 'image_height' => 675, 'image_alt' => 'SkillsPark Train the Trainers participants developing instructional and leadership skills.', 'seo_title' => 'Train the Trainers | SkillsPark Tech Hub', 'seo_description' => 'SkillsPark Train the Trainers develops communication, classroom management, public speaking, leadership and instructional ability.', 'featured' => true, 'published' => true, 'sort_order' => 5],
        ['title' => 'Special Classes', 'slug' => 'special-classes', 'eyebrow' => 'Personalized learning', 'summary' => 'A learning path built around one learner.', 'body' => 'Special Classes provide a more personalized learning experience for people who need individual attention, flexible scheduling or a course arrangement tailored around a particular goal. They may include one tutor working with one learner, flexible scheduling, delivery arrangements agreed around the learner, or a custom course request for discussion. Current pricing and schedule details are confirmed directly rather than published from legacy material.', 'audience' => 'Learners who need individual attention or a tailored learning arrangement', 'approach' => 'One-on-one or custom learning planned around the learner\'s goal and context.', 'skills' => ['Basic Special Class', 'Premium Special Class', 'Custom Course discussion', 'Flexible learner support'], 'related_audiences' => ['Children & Teenagers', 'Students & Graduates', 'Adults & Entrepreneurs'], 'seo_title' => 'Special Classes | SkillsPark Tech Hub', 'seo_description' => 'Personalized one-on-one and custom SkillsPark learning arrangements for learners with specific goals.', 'featured' => true, 'published' => true, 'sort_order' => 6],
        ['title' => 'Computer Hardware & Repairs', 'slug' => 'computer-hardware-repairs', 'eyebrow' => 'Evidence-backed course area', 'summary' => 'Understand computer components, diagnosis principles and responsible maintenance through practice.', 'body' => 'SkillsPark hardware training introduces learners to the components that make a computer work and develops practical ability in diagnosis, troubleshooting and maintenance. Learners work directly with hardware so they can understand common faults, investigate likely causes and practise appropriate repair and maintenance techniques.', 'audience' => 'Young people and adults seeking technical foundations', 'approach' => 'Practical hardware explanation, careful diagnosis and supervised maintenance activity.', 'skills' => ['Computer components', 'Safety', 'Diagnosis', 'Troubleshooting', 'Maintenance', 'Repair practice'], 'related_audiences' => ['Students & Graduates', 'Adults & Entrepreneurs'], 'image' => 'images/training/computer-hardware/computer-hardware-training-group', 'image_width' => 1200, 'image_height' => 900, 'image_alt' => 'SkillsPark learners in a hands-on computer hardware training session.', 'seo_title' => 'Computer Hardware Repairs Training | SkillsPark Tech Hub', 'seo_description' => 'Hands-on SkillsPark computer hardware training covering components, diagnosis, troubleshooting, maintenance and repair practice.', 'featured' => false, 'published' => true, 'sort_order' => 20],
    ],
    'course_catalogue' => [
        ['title' => 'Web & Software', 'summary' => 'Practical web and software-facing skills taught inside broader SkillsPark programs.', 'courses' => [
            ['title' => 'Web Design', 'description' => 'Create practical website pages and digital presence foundations.', 'programs' => ['Digital Skills Switch', 'Digital Skills Masterclass']],
            ['title' => 'Web Development', 'description' => 'Go deeper into how websites are structured, styled and made interactive.', 'programs' => ['Digital Skills Masterclass']],
            ['title' => 'Blogging', 'description' => 'Use publishing tools to organize and share useful written content.', 'programs' => ['Digital Skills Switch']],
        ]],
        ['title' => 'Design & Creative Media', 'summary' => 'Visual communication, design and media skills for creative and business use.', 'courses' => [
            ['title' => 'Graphic Design', 'description' => 'Build practical design confidence through layouts, logos, flyers and visual communication.', 'programs' => ['Digital Skills Switch', 'Digital Skills Masterclass']],
            ['title' => 'Photography', 'description' => 'Practise image capture and editing as part of creative digital work.', 'programs' => ['Digital Skills Switch']],
            ['title' => 'Video Editing / Video Content Creation', 'description' => 'Move from planning and scripting into production and final edits.', 'programs' => ['Digital Skills Switch']],
            ['title' => 'UI/UX Design', 'description' => 'Study interface and experience design through focused project work.', 'programs' => ['Digital Skills Masterclass']],
        ]],
        ['title' => 'Animation & Visual Production', 'summary' => 'Animation, motion and production skills for learners ready to specialize.', 'courses' => [
            ['title' => '2D Animation', 'description' => 'Explore character, movement, voice-over integration and digital storytelling.', 'programs' => ['Digital Skills Masterclass']],
            ['title' => '3D Modelling & Animation', 'description' => 'Develop 3D visual-production understanding through guided practice.', 'programs' => ['Digital Skills Masterclass']],
            ['title' => 'VFX & Motion Graphics', 'description' => 'Practise visual effects and motion concepts inside a specialized learning path.', 'programs' => ['Digital Skills Masterclass']],
            ['title' => 'AI-Assisted Animation', 'description' => 'Explore AI-supported animation workflows where appropriate to the class.', 'programs' => ['Digital Skills Masterclass']],
        ]],
        ['title' => 'Business & Digital Marketing', 'summary' => 'Digital business capabilities for entrepreneurs, founders and growing teams.', 'courses' => [
            ['title' => 'Digital Marketing', 'description' => 'Understand practical channels and planning for online business communication.', 'programs' => ['Digital Skills Masterclass', 'Business in the Digital Age']],
            ['title' => 'Social Media Marketing', 'description' => 'Use social platforms more intentionally for business communication.', 'programs' => ['Business in the Digital Age']],
            ['title' => 'Entrepreneurship & Business Skills', 'description' => 'Connect practical digital learning with enterprise thinking and execution.', 'programs' => ['Digital Skills Switch', 'Business in the Digital Age']],
            ['title' => 'AI for Business', 'description' => 'Explore practical ways AI tools can support everyday business activity.', 'programs' => ['Business in the Digital Age']],
            ['title' => 'Branding & Packaging', 'description' => 'Improve how products and services are presented to customers.', 'programs' => ['Business in the Digital Age']],
        ]],
        ['title' => 'Technical & Hardware', 'summary' => 'Hands-on technical skills for understanding, maintaining, building or repairing technology.', 'courses' => [
            ['title' => 'Computer Maintenance', 'description' => 'Learn components, fault detection, troubleshooting and maintenance practice.', 'programs' => ['Technical Skills Program'], 'url' => '/training/program/computer-hardware-repairs'],
            ['title' => 'Smartphone Repairs', 'description' => 'A practical technical area available for confirmed SkillsPark delivery.', 'programs' => ['Technical Skills Program']],
            ['title' => 'Robotics', 'description' => 'Explore fundamentals, simple robot construction and programming concepts using C++.', 'programs' => ['Technical Skills Program']],
        ]],
    ],
];
