<?php

declare(strict_types=1);

return [
    'audiences' => [
        ['title' => 'Children & Teenagers', 'slug' => 'children-and-teenagers', 'summary' => 'Guided, age-aware technology experiences that build curiosity, confidence and safe creative habits.', 'skills' => ['Coding foundations', 'Robotics', 'Creative design', 'Digital safety', 'Project presentation'], 'outcomes' => ['Understand core digital concepts', 'Create a guided practical project', 'Communicate what was learned'], 'format' => 'Small-group or institutional delivery', 'duration' => 'Configured for the selected program', 'location' => 'Available locations are confirmed during enquiry', 'requirements' => 'Age, device access and guardian or school consent are confirmed before delivery', 'published' => true, 'sort_order' => 1, 'seo_title' => 'Technology Training for Children and Teenagers | SkillsPark', 'seo_description' => 'Project-based coding, robotics and creative technology programs for young learners.'],
        ['title' => 'Students & Graduates', 'slug' => 'students-and-graduates', 'summary' => 'Applied digital skills and portfolio-focused projects for employment, enterprise and continued learning.', 'skills' => ['Web development', 'UI/UX', 'Graphic design', 'AI productivity', 'Digital business'], 'outcomes' => ['Complete practical project work', 'Develop stronger problem-solving habits', 'Identify a realistic development pathway'], 'format' => 'Cohort, workshop or partner delivery', 'duration' => 'Depends on depth and selected skills', 'location' => 'Confirmed for each engagement', 'requirements' => 'Requirements vary by pathway and are shared before enrolment', 'published' => true, 'sort_order' => 2, 'seo_title' => 'Digital Skills for Students and Graduates | SkillsPark', 'seo_description' => 'Practical technology training for portfolio development, work and entrepreneurship.'],
        ['title' => 'Adults & Entrepreneurs', 'slug' => 'adults-and-entrepreneurs', 'summary' => 'Useful technology skills for work, productivity, business development and independent projects.', 'skills' => ['Digital productivity', 'Web and design skills', 'AI tools', 'Online business', 'Content creation'], 'outcomes' => ['Use selected tools with more confidence', 'Apply skills to a real work or business need', 'Leave with practical next steps'], 'format' => 'Workshop, short course or tailored small-group training', 'duration' => 'Configured around the learning goal', 'location' => 'Confirmed during enquiry', 'requirements' => 'No assumptions are made about prior experience; entry needs are agreed first', 'published' => true, 'sort_order' => 3, 'seo_title' => 'Technology Training for Adults and Entrepreneurs | SkillsPark', 'seo_description' => 'Practical digital skills for productivity, employment, business and creative work.'],
        ['title' => 'Schools', 'slug' => 'schools', 'summary' => 'Technology programs, clubs and staff development aligned with a school’s learners, calendar and resources.', 'skills' => ['Coding and robotics', 'Digital creativity', 'Teacher productivity', 'Technology planning', 'Responsible technology use'], 'outcomes' => ['Structured learning experiences', 'Better staff confidence with selected tools', 'A realistic plan for ongoing technology development'], 'format' => 'On-site, partner venue or blended institutional delivery', 'duration' => 'Agreed with the school', 'location' => 'Serving schools in agreed locations, including Abuja outreach', 'requirements' => 'Safeguarding, consent, facilities and responsibilities are agreed in advance', 'published' => true, 'sort_order' => 4, 'seo_title' => 'Technology Programs and Training for Schools | SkillsPark', 'seo_description' => 'Student programs, technology clubs and staff capacity development for schools.'],
        ['title' => 'Corporate Training', 'slug' => 'corporate-training', 'summary' => 'Role-relevant staff training designed around organizational priorities and real workplace tasks.', 'skills' => ['Digital productivity', 'AI at work', 'Documentation systems', 'Digital communication', 'Team-specific technology'], 'outcomes' => ['Apply tools to real responsibilities', 'Use shared methods more consistently', 'Identify workflow improvements'], 'format' => 'On-site, remote or blended team delivery', 'duration' => 'Defined after a needs assessment', 'location' => 'Delivered for organizations in agreed locations', 'requirements' => 'A brief needs assessment identifies roles, tools and expected outcomes', 'published' => true, 'sort_order' => 5, 'seo_title' => 'Corporate Technology Training | SkillsPark', 'seo_description' => 'Tailored digital productivity, AI and technology training for teams and organizations.'],
    ],
    'programs' => [
        ['title' => 'Web Development Foundations', 'slug' => 'web-development-foundations', 'summary' => 'Learn how modern websites are structured, styled and made interactive through guided projects.', 'audience' => 'Students, graduates, adults and entrepreneurs', 'skills' => ['HTML', 'CSS', 'JavaScript foundations', 'Responsive design', 'Project workflow'], 'featured' => true, 'published' => true, 'sort_order' => 1],
        ['title' => 'Creative Design & Visual Communication', 'slug' => 'creative-design', 'summary' => 'Build visual thinking and practical design habits for digital and print communication.', 'audience' => 'Young people, students, entrepreneurs and teams', 'skills' => ['Design principles', 'Layout', 'Typography', 'Brand assets', 'Presentation'], 'featured' => true, 'published' => true, 'sort_order' => 2],
        ['title' => 'Robotics & Creative Technology', 'slug' => 'robotics-creative-technology', 'summary' => 'Explore computing and engineering ideas through guided making, testing and presentation.', 'audience' => 'Children, teenagers and school groups', 'skills' => ['Logical thinking', 'Basic electronics', 'Programming concepts', 'Team projects'], 'featured' => true, 'published' => true, 'sort_order' => 3],
        ['title' => 'AI & Digital Productivity', 'slug' => 'ai-digital-productivity', 'summary' => 'Use modern digital tools responsibly to research, organize, communicate and complete work.', 'audience' => 'Adults, entrepreneurs, students and teams', 'skills' => ['Prompting foundations', 'Verification', 'Document workflows', 'Responsible use'], 'featured' => true, 'published' => true, 'sort_order' => 4],
        ['title' => 'Computer Hardware & Repairs', 'slug' => 'computer-hardware-repairs', 'summary' => 'Understand computer components, diagnosis principles and responsible maintenance through practice.', 'audience' => 'Young people and adults seeking technical foundations', 'skills' => ['Components', 'Safety', 'Diagnosis', 'Maintenance', 'Repair decision-making'], 'featured' => false, 'published' => true, 'sort_order' => 5],
        ['title' => 'Train the Trainers', 'slug' => 'train-the-trainers', 'summary' => 'Develop the confidence, communication and instructional ability to help others learn practical skills.', 'body' => 'SkillsPark\'s Train the Trainers programme helps learners develop the ability to pass on the skills they have gained. Participants strengthen communication, classroom management, public speaking, leadership and confidence while learning how to guide others effectively. Some participants are also empowered to support learning as tutors or instructors, creating an early pathway into practical work while extending knowledge to more people.', 'audience' => 'Learners ready to strengthen leadership and instructional ability', 'skills' => ['Communication', 'Classroom management', 'Public speaking', 'Leadership', 'Instructional ability'], 'image' => 'images/training/train-the-trainers/train-the-trainers', 'image_width' => 1200, 'image_height' => 675, 'image_alt' => 'SkillsPark Train the Trainers participants developing instructional and leadership skills.', 'seo_title' => 'Train the Trainers | SkillsPark Tech Hub', 'seo_description' => 'SkillsPark Train the Trainers develops communication, classroom management, public speaking, leadership and instructional ability.', 'featured' => false, 'published' => true, 'sort_order' => 6],
        ['title' => 'Digital Skills Switch', 'slug' => 'digital-skills-switch', 'summary' => 'Use graphic design as an accessible starting point for computer confidence and practical digital skills.', 'body' => 'For learners with little or no previous computer experience, SkillsPark uses graphic design as a practical entry point into digital skills. Early sessions build confidence with the laptop, touchpad, files and essential computer operations before learners begin creating their own work. By the end of the foundation stage, participants can apply those skills to practical designs such as logos, ID cards and flyers, giving them a base they can continue developing inside the programme or independently.', 'audience' => 'Learners with little or no previous computer experience', 'skills' => ['Laptop use', 'Touchpad control', 'Basic computer operation', 'File and navigation confidence', 'Graphic design foundations'], 'image' => 'images/training/digital-skills-switch-graphic-design/digital-skills-switch-graphic-design', 'image_width' => 1200, 'image_height' => 675, 'image_alt' => 'SkillsPark learners building computer confidence through practical graphic design.', 'seo_title' => 'Digital Skills Switch | SkillsPark Tech Hub', 'seo_description' => 'SkillsPark Digital Skills Switch uses graphic design to help learners build basic computer confidence and practical digital skills.', 'featured' => false, 'published' => true, 'sort_order' => 7],
    ],
];
