<?php
$title = 'Contact SkillsPark Tech Hub.';
$eyebrow = 'Contact';
$intro = 'Ask about technology services, practical training, partnerships or EdixPark in Kano and Abuja.';
$breadcrumbs = [['label' => 'Home', 'url' => '/'], ['label' => 'Contact', 'url' => '/contact']];
require ROOT_PATH . '/app/views/components/page-hero.php';
$contact = config('contact');
?>
<section class="section"><div class="container"><div class="section-heading"><p class="eyebrow">Contact methods</p><h2>Choose the easiest way to reach us.</h2></div><div class="contact-method-grid"><a class="contact-method-card" href="<?= h($contact['phone_uri']) ?>"><?= icon('phone') ?><span><strong>Call SkillsPark</strong><small><?= h($contact['phone']) ?></small></span></a><a class="contact-method-card contact-method-card--primary" href="<?= h(whatsapp_url('Hello SkillsPark, I would like to make an enquiry.')) ?>" target="_blank" rel="noopener noreferrer"><?= icon('chat') ?><span><strong>WhatsApp SkillsPark</strong><small><?= h($contact['whatsapp']) ?></small></span></a><a class="contact-method-card" href="<?= h($contact['email_uri']) ?>"><?= icon('mail') ?><span><strong>Email SkillsPark</strong><small class="wrap-link"><?= h($contact['email']) ?></small></span></a></div></div></section>
<section class="section section--soft"><div class="container"><div class="section-heading"><p class="eyebrow">Locations & presence</p><h2>Based in Kano and serving Abuja.</h2></div><div class="location-grid"><article class="card"><span class="icon-box"><?= icon('map') ?></span><p class="kicker">Primary location</p><h3><?= h($contact['locations']['primary']) ?></h3></article><article class="card"><span class="icon-box"><?= icon('map') ?></span><p class="kicker">Service presence</p><h3><?= h($contact['locations']['abuja']) ?></h3><p>Contact SkillsPark through the general phone number, WhatsApp or email shown on this page.</p></article></div></div></section>
<section class="section"><div class="container contact-grid"><div><div class="section-heading"><p class="eyebrow">Enquiry form</p><h2>Tell us what you need.</h2></div><?php $formType='contact'; require ROOT_PATH . '/app/views/components/form.php'; ?></div><?php require ROOT_PATH . '/app/views/components/contact-options.php'; ?></div></section>
<section class="section section--soft"><div class="container"><div class="section-heading"><p class="eyebrow">Social channels</p><h2>Follow SkillsPark online.</h2></div><ul class="social-link-grid"><?php foreach ($contact['socials'] as $social): $socialUrl = safe_external_url($social['url']); if ($socialUrl): ?><li><a href="<?= h($socialUrl) ?>" target="_blank" rel="noopener noreferrer"><?= h($social['label']) ?> <?= icon('arrow') ?></a></li><?php endif; endforeach; ?></ul></div></section>
