<?php $product = content('edixpark'); $website = safe_external_url($product['website']); ?>
<section class="edixpark-hero">
    <div class="container edixpark-hero__grid">
        <div>
            <p class="eyebrow">Education technology platform</p>
            <img class="edixpark-logo" src="<?= h(asset('images/edixpark/edixpark-logo.png')) ?>" width="1600" height="305" alt="EdixPark">
            <h1>Digital infrastructure for school operations, online learning and institutional growth.</h1>
            <p class="lead">EdixPark helps educational institutions organize daily operations, deliver branded learning programmes, manage learners and expand their digital delivery through one flexible product family.</p>
            <div class="button-row"><a class="button" href="<?= h($website) ?>" target="_blank" rel="noopener noreferrer" aria-label="Visit EdixPark.com (opens in a new tab)">Visit EdixPark.com <?= icon('arrow') ?></a><a class="button button--outline" href="#product-family">Explore the EdixPark product family</a></div>
        </div>
        <aside class="edixpark-hero__note"><p>Built within SkillsPark. Operated as a dedicated education-technology platform.</p><p>School, Learn and Suite form one connected education ecosystem.</p></aside>
    </div>
</section>
<section class="section section--soft" id="product-family"><div class="container"><div class="section-heading"><p class="eyebrow">EdixPark product family</p><h2>Three product paths. One connected education ecosystem.</h2></div><div class="edixpark-products"><?php foreach ($product['products'] as $item): $productUrl = safe_external_url($item['url']); ?><article><p class="eyebrow"><?= h($item['purpose']) ?></p><h3><?= h($item['title']) ?></h3><p><?= h($item['summary']) ?></p><a class="text-link" href="<?= h($productUrl) ?>" target="_blank" rel="noopener noreferrer" aria-label="<?= h($item['label']) ?> (opens in a new tab)"><?= h($item['label']) ?> <?= icon('arrow') ?></a></article><?php endforeach; ?></div></div></section>
<section class="section"><div class="container"><div class="section-heading"><p class="eyebrow">What EdixPark enables</p><h2>One platform family for the work around learning.</h2></div><div class="edixpark-capabilities"><?php foreach ($product['capabilities'] as $index => $item): ?><article><span>0<?= h($index + 1) ?></span><h3><?= h($item['title']) ?></h3><p><?= h($item['summary']) ?></p></article><?php endforeach; ?></div></div></section>
<section class="section section--navy"><div class="container story-block__grid"><div><p class="eyebrow">Branded online learning</p><h2>From physical operations to digital learning delivery.</h2><p>EdixPark Learn gives educational organizations their own branded learning environment for structured courses, learner enrolment, free and paid programmes, assessments, certificates, live classes, and recorded or blended learning.</p></div><div class="edixpark-growth"><p>Start with School for operational management.</p><p>Start with Learn for online academy or course delivery.</p><p>Use Suite when operations and learning infrastructure need to work together.</p></div></div></section>
<section class="section"><div class="container story-block__grid"><div><p class="eyebrow">Who EdixPark serves</p><h2>Built for institutions that deliver education.</h2><p>EdixPark is designed for a range of educational environments, without implying that every organization listed is already a customer.</p></div><ul class="edixpark-audiences"><?php foreach ($product['audiences'] as $audience): ?><li><?= h($audience) ?></li><?php endforeach; ?></ul></div></section>
<section class="section section--soft" id="flexibility"><div class="container"><div class="section-heading"><p class="eyebrow">Flexibility</p><h2>Built around the institution, not the other way around.</h2><p>Institutions can configure the platform around their actual structure without being forced into one fixed operating model.</p></div><div class="edixpark-flexibility"><?php foreach ($product['flexibility'] as $index => $item): ?><article><span>0<?= h($index + 1) ?></span><h3><?= h($item['title']) ?></h3><p><?= h($item['summary']) ?></p></article><?php endforeach; ?></div></div></section>
<section class="section"><div class="container story-block__grid"><div><p class="eyebrow">SkillsPark relationship</p><h2>Built within the SkillsPark technology ecosystem.</h2></div><div><p>SkillsPark develops people, technology and digital solutions. EdixPark emerged from that ecosystem as a dedicated education-technology platform focused on digital education infrastructure.</p><p>EdixPark operates with its own product identity, platform experience, administration and dedicated website. It is not a SkillsPark service or training programme.</p><a class="text-link" href="<?= h($website) ?>" target="_blank" rel="noopener noreferrer" aria-label="Visit EdixPark.com (opens in a new tab)">Visit EdixPark.com <?= icon('arrow') ?></a></div></div></section>
<section class="section section--navy"><div class="container story-block__grid"><div><p class="eyebrow">Product milestone</p><h2>Launched 18 May 2026.</h2><p>EdixPark was developed as part of SkillsPark's expansion into education technology. Muhammad-Dayyib Idris contributed to its development and is founder and CEO associated with both SkillsPark Tech Hub and EdixPark.</p></div><div><p class="eyebrow">Official platform</p><h2>Explore the complete EdixPark experience.</h2><p>The dedicated EdixPark website provides the current product information and platform experience.</p><a class="text-link text-link--light" href="<?= h($website) ?>" target="_blank" rel="noopener noreferrer" aria-label="Visit EdixPark.com (opens in a new tab)">Visit EdixPark.com <?= icon('arrow') ?></a></div></div></section>
<script type="application/ld+json"><?= json_for_html(['@context'=>'https://schema.org','@type'=>'SoftwareApplication','name'=>'EdixPark','description'=>'Digital education infrastructure for school operations and online learning.','url'=>$website,'applicationCategory'=>'EducationalApplication','provider'=>['@type'=>'Organization','name'=>'SkillsPark Tech Hub','url'=>url('/')]]) ?></script>
