<?php
$profile=content('founder');
$hasVerifiedProfile=(bool)($profile['name']||$profile['photo']||$profile['short_bio']||$profile['full_story']||$profile['expertise']||$profile['achievements']||$profile['programs']||$profile['media']);
$displayName=$profile['name'] ?: 'Founder profile';
$title=$displayName;
$eyebrow='Founder profile';
$intro=$profile['short_bio'] ?: 'SkillsPark is preparing a verified founder profile.';
$breadcrumbs=[['label'=>'Home','url'=>'/'],['label'=>'Founder','url'=>'/founder']];
require ROOT_PATH . '/app/views/components/page-hero.php';
?>
<?php if($hasVerifiedProfile): ?>
<section class="section"><div class="container founder-layout"><div><?php if($profile['photo']): ?><picture class="founder-media founder-media--large"><source type="image/webp" srcset="<?= h($profile['photo_webp_srcset']) ?>" sizes="(max-width: 860px) min(100vw - 32px, 560px), 560px"><img class="founder-photo" src="<?= h(url($profile['photo'])) ?>" srcset="<?= h($profile['photo_srcset']) ?>" sizes="(max-width: 860px) min(100vw - 32px, 560px), 560px" alt="<?= h($profile['photo_alt']) ?>" width="720" height="900" loading="lazy"></picture><?php else: ?><div class="founder-placeholder founder-placeholder--large" aria-label="Founder photograph has not been supplied"><?= icon('person') ?></div><?php endif; ?></div><div><p class="eyebrow"><?= h($profile['headline']) ?></p><h2>From teaching technology to building technology.</h2><p class="standfirst"><?= h($profile['journey']) ?></p><?php if($profile['full_story']): ?><div class="prose"><p><?= nl2br(h($profile['full_story'])) ?></p></div><?php endif; ?><?php if($profile['availability']): ?><div class="availability"><h3>Available for</h3><?php foreach($profile['availability'] as $item): ?><span><?= h($item) ?></span><?php endforeach; ?></div><?php endif; ?></div></div></section>
<?php if($profile['expertise']): ?><section class="section section--soft"><div class="container"><div class="section-heading"><p class="eyebrow">Areas of expertise</p><h2>Professional focus.</h2></div><ul class="feature-list"><?php foreach($profile['expertise'] as $item): ?><li><?= icon('check') ?><span><?= h($item) ?></span></li><?php endforeach; ?></ul></div></section><?php endif; ?>
<section class="section founder-editorial"><div class="container story-block__grid"><picture class="founder-media founder-media--large reveal"><source type="image/webp" srcset="<?= h(asset('images/founder/muhammad-dayyib-idris-skillspark/muhammad-dayyib-idris-skillspark-480.webp')) ?> 480w, <?= h(asset('images/founder/muhammad-dayyib-idris-skillspark/muhammad-dayyib-idris-skillspark-768.webp')) ?> 768w, <?= h(asset('images/founder/muhammad-dayyib-idris-skillspark/muhammad-dayyib-idris-skillspark-1200.webp')) ?> 1200w" sizes="(max-width: 860px) min(100vw - 32px, 560px), 520px"><img class="founder-photo" src="<?= h(asset('images/founder/muhammad-dayyib-idris-skillspark/muhammad-dayyib-idris-skillspark-768.jpg')) ?>" srcset="<?= h(asset('images/founder/muhammad-dayyib-idris-skillspark/muhammad-dayyib-idris-skillspark-480.jpg')) ?> 480w, <?= h(asset('images/founder/muhammad-dayyib-idris-skillspark/muhammad-dayyib-idris-skillspark-768.jpg')) ?> 768w, <?= h(asset('images/founder/muhammad-dayyib-idris-skillspark/muhammad-dayyib-idris-skillspark-1200.jpg')) ?> 1200w" sizes="(max-width: 860px) min(100vw - 32px, 560px), 520px" width="1200" height="1600" loading="lazy" alt="Muhammad-Dayyib Idris pictured in connection with SkillsPark branding."></picture><div class="reveal"><p class="eyebrow">WHY SKILLSPARK EXISTS</p><h2>Building capability that can change what people and organizations are able to do.</h2><p>SkillsPark Tech Hub was built around a simple belief: technology becomes most valuable when people can use it to build, solve problems and create opportunity. Our work connects practical learning, technology services and education innovation so individuals and organizations can move from ideas to useful outcomes.</p><p>We want SkillsPark to be a place where learning becomes capability, capability becomes useful work, and technology becomes a tool for meaningful progress.</p><p><strong>Muhammad-Dayyib Idris</strong><br>Founder & CEO, SkillsPark Tech Hub</p></div></div></section>
<section class="section section--soft founder-editorial"><div class="container story-block__grid story-block__grid--reverse"><div class="reveal"><p class="eyebrow">REFLECTION & IMPROVEMENT</p><h2>Progress needs time to be reviewed, not only spent.</h2><p>One practice I value is creating time to review the work behind me before rushing into what comes next. Reflection makes it easier to see what moved forward, what did not work, what should change and where more attention is needed.</p><p>Time is one of our most limited resources. Giving yourself a quiet moment to review how it was used can turn experience into better decisions and create space for new ideas.</p><p><strong>Muhammad-Dayyib Idris</strong></p></div><picture class="founder-media founder-media--large reveal"><source type="image/webp" srcset="<?= h(asset('images/founder/muhammad-dayyib-idris-reflection/muhammad-dayyib-idris-reflection-480.webp')) ?> 480w, <?= h(asset('images/founder/muhammad-dayyib-idris-reflection/muhammad-dayyib-idris-reflection-768.webp')) ?> 768w, <?= h(asset('images/founder/muhammad-dayyib-idris-reflection/muhammad-dayyib-idris-reflection-1200.webp')) ?> 1200w" sizes="(max-width: 860px) min(100vw - 32px, 560px), 520px"><img class="founder-photo" src="<?= h(asset('images/founder/muhammad-dayyib-idris-reflection/muhammad-dayyib-idris-reflection-768.jpg')) ?>" srcset="<?= h(asset('images/founder/muhammad-dayyib-idris-reflection/muhammad-dayyib-idris-reflection-480.jpg')) ?> 480w, <?= h(asset('images/founder/muhammad-dayyib-idris-reflection/muhammad-dayyib-idris-reflection-768.jpg')) ?> 768w, <?= h(asset('images/founder/muhammad-dayyib-idris-reflection/muhammad-dayyib-idris-reflection-1200.jpg')) ?> 1200w" sizes="(max-width: 860px) min(100vw - 32px, 560px), 520px" width="1200" height="1600" loading="lazy" alt="Muhammad-Dayyib Idris in a reflective work setting."></picture></div></section>
<section class="section founder-editorial"><div class="container story-block__grid"><picture class="founder-media founder-media--large reveal"><source type="image/webp" srcset="<?= h(asset('images/founder/muhammad-dayyib-idris-founder-portrait-office/muhammad-dayyib-idris-founder-portrait-office-480.webp')) ?> 480w, <?= h(asset('images/founder/muhammad-dayyib-idris-founder-portrait-office/muhammad-dayyib-idris-founder-portrait-office-768.webp')) ?> 768w, <?= h(asset('images/founder/muhammad-dayyib-idris-founder-portrait-office/muhammad-dayyib-idris-founder-portrait-office-1200.webp')) ?> 1200w" sizes="(max-width: 860px) min(100vw - 32px, 560px), 520px"><img class="founder-photo" src="<?= h(asset('images/founder/muhammad-dayyib-idris-founder-portrait-office/muhammad-dayyib-idris-founder-portrait-office-768.jpg')) ?>" srcset="<?= h(asset('images/founder/muhammad-dayyib-idris-founder-portrait-office/muhammad-dayyib-idris-founder-portrait-office-480.jpg')) ?> 480w, <?= h(asset('images/founder/muhammad-dayyib-idris-founder-portrait-office/muhammad-dayyib-idris-founder-portrait-office-768.jpg')) ?> 768w, <?= h(asset('images/founder/muhammad-dayyib-idris-founder-portrait-office/muhammad-dayyib-idris-founder-portrait-office-1200.jpg')) ?> 1200w" sizes="(max-width: 860px) min(100vw - 32px, 560px), 520px" width="1200" height="1600" loading="lazy" alt="Muhammad-Dayyib Idris in an office portrait for SkillsPark founder content."></picture><div class="reveal"><p class="eyebrow">LESSONS FROM THE JOURNEY</p><h2>Three ideas I keep returning to.</h2><div class="principles-list"><div><span>01</span><p><strong>Give meaningful work time.</strong><br>Important things rarely become strong overnight. Building skills, trust, experience and useful work takes patience and sustained effort.</p></div><div><span>02</span><p><strong>Learn how to move through failure.</strong><br>Failure can become useful when it is examined rather than hidden. The goal is not to avoid every setback, but to learn, adapt and continue with better understanding.</p></div><div><span>03</span><p><strong>Go looking for opportunity.</strong><br>People cannot respond to work they never encounter. Share the idea, enter new rooms, speak to people, ask questions and look actively for the opportunities that match what you are building.</p></div></div><p class="founder-book-note">Book from the journey - coming soon</p></div></div></section>
<?php $ctaTitle='Invite the founder to speak, train or consult.'; $ctaText='Share the audience, topic, location and intended outcome so availability can be discussed.'; require ROOT_PATH . '/app/views/components/cta.php'; ?>
<?php else: ?>
<section class="section"><div class="container narrow"><p class="eyebrow">Profile verification</p><h2>A verified founder profile is being prepared.</h2><p class="standfirst">Until biographical details, media and availability are confirmed, SkillsPark shares its work and education technology platform through the pages below.</p><div class="button-row"><a class="button" href="<?= h(url('/about')) ?>">About SkillsPark</a><a class="button button--outline" href="<?= h(url('/edixpark')) ?>">Explore EdixPark</a></div></div></section>
<?php endif; ?>
<section class="section section--navy"><div class="container story-block__grid"><div><p class="eyebrow">SkillsPark</p><h2>Developing people and helping organizations apply technology.</h2><a class="text-link text-link--light" href="<?= h(url('/about')) ?>">About SkillsPark <?= icon('arrow') ?></a></div><div><p class="eyebrow">EdixPark</p><h2>Building digital infrastructure for education.</h2><a class="text-link text-link--light" href="<?= h(url('/edixpark')) ?>">Explore EdixPark <?= icon('arrow') ?></a></div></div></section>
