<?php
$title='A visual record, published with care.'; $eyebrow='Gallery'; $intro='SkillsPark media is organized by activity and shown publicly only when publication status and consent are confirmed.'; $breadcrumbs=[['label'=>'Home','url'=>'/'],['label'=>'Gallery','url'=>'/gallery']]; require ROOT_PATH . '/app/views/components/page-hero.php';
$items=array_values(array_filter(published(content('gallery')),static fn($item)=>($item['consent_confirmed']??false)===true));
$categories=array_values(array_unique(array_column($items,'category')));
?>
<section class="section"><div class="container">
<?php if ($items): ?>
<div class="filter-bar" role="group" aria-label="Filter gallery"><button class="is-active" type="button" data-filter="all" aria-pressed="true">All</button><?php foreach($categories as $category): ?><button type="button" data-filter="<?= h(strtolower(str_replace(' ','-',$category))) ?>" aria-pressed="false"><?= h($category) ?></button><?php endforeach; ?></div>
<div class="gallery-grid" data-gallery><?php foreach($items as $index=>$item): ?><figure class="gallery-item reveal" data-category="<?= h(strtolower(str_replace(' ','-',$item['category']))) ?>" data-album="<?= h($item['album']??'') ?>"><button type="button" data-lightbox-index="<?= $index ?>" aria-label="Open <?= h($item['title']) ?> in media viewer"><picture><?php if(!empty($item['webp_srcset'])): ?><source type="image/webp" srcset="<?= h($item['webp_srcset']) ?>" sizes="(max-width: 600px) 100vw, 33vw"><?php endif; ?><img src="<?= h(url($item['image'])) ?>" <?= !empty($item['srcset']) ? 'srcset="'.h($item['srcset']).'" sizes="(max-width: 600px) 100vw, 33vw"' : '' ?> width="720" height="540" loading="lazy" alt="<?= h($item['alt']) ?>"></picture><?php if(($item['type']??'image')==='video'): ?><span class="video-badge"><?= icon('video') ?> Play video</span><?php endif; ?></button><figcaption><strong><?= h($item['title']) ?></strong><span><?= h($item['caption']) ?></span><?php if($item['date']||$item['location']): ?><small><?= h(trim($item['date'].' · '.$item['location'],' ·')) ?></small><?php endif; ?></figcaption></figure><?php endforeach; ?></div>
<dialog class="lightbox" data-lightbox aria-label="Media viewer"><div class="lightbox__bar"><p data-lightbox-title></p><button type="button" data-lightbox-close aria-label="Close media viewer"><?= icon('close') ?></button></div><div class="lightbox__stage"><button type="button" data-lightbox-prev aria-label="Previous media"><?= icon('chevron-left') ?></button><div class="lightbox__media"><img data-lightbox-image alt=""><iframe data-lightbox-video title="Gallery video" hidden allow="fullscreen" referrerpolicy="strict-origin-when-cross-origin"></iframe></div><button type="button" data-lightbox-next aria-label="Next media"><?= icon('chevron') ?></button></div><p data-lightbox-caption></p></dialog>
<script type="application/json" id="gallery-data"><?= json_for_html(array_map(static fn($item)=>['type'=>$item['type']??'image','src'=>url($item['image']),'video'=>safe_video_embed_url($item['video_url']??''),'alt'=>$item['alt'],'title'=>$item['title'],'caption'=>$item['caption']],$items)) ?></script>
<?php else: ?><div class="empty-state"><span><?= icon('image') ?></span><h2>No approved gallery media is published yet.</h2><p>Images appear here only after consent, ownership and publication status have been confirmed.</p></div><?php endif; ?>
</div></section>
