<?php $title=$service['title']; $eyebrow='SkillsPark service'; $intro=$service['summary']; $breadcrumbs=[['label'=>'Home','url'=>'/'],['label'=>'Services','url'=>'/services'],['label'=>$service['title'],'url'=>'/services/'.$service['slug']]]; $heroActions=[['label'=>'Discuss This Service','url'=>'/request-consultation']]; require ROOT_PATH . '/app/views/components/page-hero.php'; ?>
<script type="application/ld+json"><?= json_for_html(['@context'=>'https://schema.org','@type'=>'Service','name'=>$service['title'],'description'=>$service['summary'],'provider'=>['@type'=>'Organization','name'=>'SkillsPark Tech Hub','url'=>url('/')]]) ?></script>
<section class="section"><div class="container detail-grid"><div><p class="eyebrow">The problem</p><h2><?= h($service['problem']) ?></h2></div><aside class="card"><h2>Who it is for</h2><ul class="check-list"><?php foreach ($service['customers'] as $customer): ?><li><?= icon('check') ?><?= h($customer) ?></li><?php endforeach; ?></ul></aside></div></section>
<section class="section section--soft"><div class="container detail-grid"><div><p class="eyebrow">Key deliverables</p><h2>What an engagement may include.</h2><ul class="feature-list"><?php foreach ($service['deliverables'] as $item): ?><li><?= icon('check') ?><span><?= h($item) ?></span></li><?php endforeach; ?></ul></div><div><p class="eyebrow">Our approach</p><h2>Fit before features.</h2><p><?= h($service['approach']) ?></p><p>Exact scope, timing and responsibilities are agreed after discovery. We do not publish generic prices for work that depends on context.</p></div></div></section>
<section class="section"><div class="container"><div class="section-heading"><p class="eyebrow">Implementation process</p><h2>From need to working outcome.</h2></div><div class="process-grid process-grid--light"><?php foreach ($service['process'] as $index=>$step): ?><article><span>0<?= $index+1 ?></span><h3><?= h($step['title']) ?></h3><p><?= h($step['text']) ?></p></article><?php endforeach; ?></div></div></section>
<?php $relatedWork=array_values(array_filter(published(content('projects')),static fn($project)=>($project['related_service']??'')===$service['slug'])); $relatedServices=array_values(array_filter(published(content('services')),static fn($item)=>$item['slug']!==$service['slug'])); ?>
<section class="section section--soft"><div class="container"><div class="section-heading"><p class="eyebrow">Related work & capabilities</p><h2>See the service in context.</h2></div><?php if($relatedWork): ?><div class="case-list"><?php foreach($relatedWork as $project): ?><article class="case-row"><div><span class="tag"><?= h($project['category']) ?></span><h3><a href="<?= h(url('/work/case-studies/'.$project['slug'])) ?>"><?= h($project['title']) ?></a></h3><p><?= h($project['objective']) ?></p></div><a class="circle-link" href="<?= h(url('/work/case-studies/'.$project['slug'])) ?>" aria-label="Read related case study"><?= icon('arrow') ?></a></article><?php endforeach; ?></div><?php endif; ?><div class="card-grid card-grid--3 related-cards"><?php foreach(array_slice($relatedServices,0,3) as $item) require ROOT_PATH . '/app/views/components/service-card.php'; ?></div></div></section>
<?php if (!empty($service['faqs'])): ?><section class="section section--soft"><div class="container narrow"><div class="section-heading"><p class="eyebrow">Frequently asked questions</p><h2>Useful details before we begin.</h2></div><div class="faq-list"><?php foreach ($service['faqs'] as $faq): ?><details><summary><?= h($faq['q']) ?><?= icon('plus') ?></summary><p><?= h($faq['a']) ?></p></details><?php endforeach; ?></div></div></section><script type="application/ld+json"><?= json_for_html(['@context'=>'https://schema.org','@type'=>'FAQPage','mainEntity'=>array_map(static fn($faq)=>['@type'=>'Question','name'=>$faq['q'],'acceptedAnswer'=>['@type'=>'Answer','text'=>$faq['a']]],$service['faqs'])]) ?></script><?php endif; ?>
<?php $ctaTitle='Discuss '.$service['title'].'.'; $ctaText='Share the context, expected outcome and current constraints. We will help define the next step.'; require ROOT_PATH . '/app/views/components/cta.php'; ?>
